proxy_cache_valid 200 1d;
proxy_cache_valid 404 1m;
proxy_cache_revalidate on;
proxy_cache_lock on;
proxy_cache_key  "$uri";

proxy_cache_path /mnt/cache/nginx/img-b2 levels=2:2 keys_zone=img-b2:100m inactive=7d max_size=200g;

server {
    listen 5400;

    location / {
       # 结尾必须要有 /
       proxy_pass https://f004.backblazeb2.com/file/xxai-jxl/;
       proxy_cache img-b2;
       proxy_cache_bypass $uri;
       proxy_cache_revalidate on;
       proxy_cache_lock on;
    }
    access_log /var/log/nginx/img-b2.log global_main;
    error_log /var/log/nginx/img-b2.error.log error;
}


proxy_cache_path /mnt/cache/nginx/img-rust levels=2:2 keys_zone=img-rust:100m inactive=7d max_size=100g;


upstream img_b2 {
  server 127.0.0.1:5500;
}

server {

  server_name 5ok.pw;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  add_header Alt-Svc 'h3=":443";ma=99999;persist=1';
  ssl_certificate /mnt/www/.acme.sh/5ok.pw_ecc/fullchain.cer;
  ssl_certificate_key /mnt/www/.acme.sh/5ok.pw_ecc/5ok.pw.key;

  location = / {
    proxy_pass http://img_b2;
  }

  location / {
    proxy_pass http://img_b2;
    proxy_cache img-rust;
    proxy_cache_bypass $uri;
    proxy_cache_revalidate on;
    proxy_cache_lock on;
  }

  access_log /var/log/nginx/img-rust.h2.log global_main;
  error_log /var/log/nginx/img-rust.h2.error.log error;
}

server {
  server_name 5ok.pw;
  listen 443 quic;
  listen [::]:443 quic;
  ssl_certificate /mnt/www/.acme.sh/5ok.pw_ecc/fullchain.cer;
  ssl_certificate_key /mnt/www/.acme.sh/5ok.pw_ecc/5ok.pw.key;

  location = / {
    proxy_pass http://img_b2;
  }

  location / {
    proxy_pass http://img_b2;
    proxy_cache img-rust;
    proxy_cache_bypass $uri;
    proxy_cache_revalidate on;
    proxy_cache_lock on;
  }

  access_log /var/log/nginx/img-rust.h3.log global_main;
  error_log /var/log/nginx/img-rust.h3.error.log error;

}

server {
  server_name smtp.xxai.art;
  listen 443 http2;
  listen [::]:443 http2;
  ssl_certificate /mnt/www/.acme.sh/xxai.art_ecc/fullchain.cer;
  ssl_certificate_key /mnt/www/.acme.sh/xxai.art_ecc/xxai.art.key;

  location = / {
    proxy_pass http://img_b2;
  }

  location / {
    proxy_pass http://img_b2;
    proxy_cache img-rust;
    proxy_cache_bypass $uri;
    proxy_cache_revalidate on;
    proxy_cache_lock on;
  }

  access_log /var/log/nginx/img-rust.h3.log global_main;
  error_log /var/log/nginx/img-rust.h3.error.log error;

}
